version: '2.0'
services:
  web:
    build: docker/apache
    ports:
    - "3600:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db
  encore:
    image: node:10-alpine
    volumes:
        - .:/app
    ports:
        - "8080"
    working_dir: /app
    command: ["yarn", "dev-server", "--host=0.0.0.0"]
  db:
    build: docker/mysql
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3311:3306"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '4005:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
